apiVersion: "apps/v1"
kind: Deployment
metadata: 
  name: petclinic-deploy
  labels:
    app: petclinic-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-deploy
  template:
    metadata:
      lables:
        app: petclinic-deploy
    spec:
      containers:
      - name: petclinic-deploy
        image: projetdevopsfn/petclinic:latest
        ports:
        - containerPort: 3080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-deploy-svc
spec: 
  type: NodePort
  ports:
  - port: 3080
   targetPort: ?
   nodePort: ?
  selector:
    app: cars-api 